# Paramètres du site
title: Le raccourcis
description: Un site qui sert uniquement de raccourcis pour quelques commandes Linux, etc ...
theme: just-the-docs
url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# fichier et répertoire à ne pas inclure

search_enabled: true

# For copy button on code
enable_copy_code_button: true
