# Paramètres du site
title: Le raccourcis
description: Un site qui sert uniquement de raccourcis pour quelques commandes Linux, etc ...
theme: just-the-docs
url: https://just-the-docs.github.io

# fichier et répertoire à ne pas inclure
exclude:
  - README.md
  - TODO.md
  - assets

search_enabled: true

# For copy button on code
enable_copy_code_button: true

# initialisation des callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
